version: "3.5"

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        restart: always
        ports:
            - "2181:2181"
        environment:
            LOG_DIR: /tmp/logs
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:latest
        restart: always
        depends_on:
            - zookeeper
        ports:
            - "29092:29092"
        environment:
            LOG_DIR: "/tmp/logs"
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    frontend:
        build:
            context: ./frontend
        restart: always
        depends_on:
            - producer
            - websocket-consumer
        ports:
            - "80:80"
    producer:
        image: eduardooolol/producer-app:latest
        restart: always
        depends_on:
            - kafka
            - zookeeper
        ports:
            - "8080:8080"
    websocket-consumer:
        image: eduardooolol/websocket-consumer-app:latest
        restart: always
        depends_on:
            - kafka
            - zookeeper
        ports:
            - "9090:9090"
