version: "3.5"

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        restart: always
        ports:
            - 2181:2181
        environment:
            LOG_DIR: /tmp/logs
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - kafka-network

    kafka-broker:
        image: confluentinc/cp-kafka:latest
        restart: always
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
            LOG_DIR: "/tmp/logs"
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - kafka-network

networks:
    kafka-network:
        name: kafkanetwork
